name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        # mac version is built locally because of the code signing
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Clean install dependencies
        run: npm ci

      - name: Build application (Windows)
        if: runner.os == 'Windows'
        run: |
          npm run make -- --arch x64
          npm run make -- --arch arm64
        env:
          NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
          NUGET_HTTP_CACHE_PATH: ${{ github.workspace }}/.nuget/cache

      - name: Build application (Linux)
        if: runner.os == 'Linux'
        run: npm run make -- --arch x64,arm64

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dmtool-${{ matrix.os }}
          path: out/make
